[package]
name = "ping-pong"
version = "0.1.0"
authors = ["Marina Gruzdeva"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"